name: Deploy on
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh -
      - uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{45ejeijdiescsdnj4fdsi}}
          heroku_app_name: "n8nnn"
          heroku_email: "dname9459@gmail.com"
